version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - nextjs
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/lib/letsencrypt
    entrypoint: /bin/sh
    command: -c "sleep 10s && certbot certonly --webroot --webroot-path=/etc/nginx/conf.d -d marsonoid.ru --email ilya.nikiforov.04@bk.ru --agree-tos --non-interactive"
    depends_on:
      - nginx
    restart: on-failure
